/*
 * C interface header file for module(s):
 *
 *   - BlasLevel1
 *
 * generated by sac4c 2.1.0-PuurGeluk-260-g7be5 (RELEASE)
 */

#include "sacinterface.h"


/*****************************************************************************
 * User Defined Type ComplexBasics::complex implemented in SaC as double[2]
 *
 * NB: to create a ComplexBasics__complex[300,200], call
 *     SACARGcreateFromPointer (SACTYPE_ComplexBasics__complex, data, 3, 300, 200, 2)
 *     with data being of type double*.
 */

SAC_C_EXTERN SACtypes *SACTYPE_ComplexBasics__complex;


/*****************************************************************************
 * User Defined Type Complex::complex implemented in SaC as double[2]
 *
 * NB: to create a Complex__complex[300,200], call
 *     SACARGcreateFromPointer (SACTYPE_Complex__complex, data, 3, 300, 200, 2)
 *     with data being of type double*.
 */

SAC_C_EXTERN SACtypes *SACTYPE_Complex__complex;


/*****************************************************************************
 * User Defined Type Structures::complex implemented in SaC as double[2]
 *
 * NB: to create a Structures__complex[300,200], call
 *     SACARGcreateFromPointer (SACTYPE_Structures__complex, data, 3, 300, 200, 2)
 *     with data being of type double*.
 */

SAC_C_EXTERN SACtypes *SACTYPE_Structures__complex;



/*****************************************************************************
 * C declaration of function BlasLevel1::idamax.
 *
 * defined instances:
 *
 *  ( int, double[.], int) -> ( int)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__idamax3(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::dcopy.
 *
 * defined instances:
 *
 *  ( int, double[.], int, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__dcopy5(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::dswap.
 *
 * defined instances:
 *
 *  ( int, double[.], int, double[.], int) -> ( double[.], double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__dswap5(SACarg **ret1, SACarg **ret2, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::drot.
 *
 * defined instances:
 *
 *  ( int, double[.], int, double[.], int, double, double) -> ( double[.], double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__drot7(SACarg **ret1, SACarg **ret2, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7);

/*****************************************************************************
 * C declaration of function BlasLevel1::dsdot.
 *
 * defined instances:
 *
 *  ( int, float[.], int, float[.], int) -> ( double)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__dsdot5(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::srotg.
 *
 * defined instances:
 *
 *  ( float, float, float, float) -> ( float, float, float, float)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__srotg4(SACarg **ret1, SACarg **ret2, SACarg **ret3, SACarg **ret4, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4);

/*****************************************************************************
 * C declaration of function BlasLevel1::isamax.
 *
 * defined instances:
 *
 *  ( int, float[.], int) -> ( int)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__isamax3(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::scopy.
 *
 * defined instances:
 *
 *  ( int, float[.], int, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__scopy5(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::sswap.
 *
 * defined instances:
 *
 *  ( int, float[.], int, float[.], int) -> ( float[.], float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__sswap5(SACarg **ret1, SACarg **ret2, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::srot.
 *
 * defined instances:
 *
 *  ( int, float[.], int, float[.], int, float, float) -> ( float[.], float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__srot7(SACarg **ret1, SACarg **ret2, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7);

/*****************************************************************************
 * C declaration of function BlasLevel1::dasum.
 *
 * defined instances:
 *
 *  ( int, double[.], int) -> ( double)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__dasum3(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::sdsdot.
 *
 * defined instances:
 *
 *  ( int, float, float[.], int, float[.], int) -> ( float)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__sdsdot6(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6);

/*****************************************************************************
 * C declaration of function BlasLevel1::sasum.
 *
 * defined instances:
 *
 *  ( int, float[.], int) -> ( float)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__sasum3(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::dscal.
 *
 * defined instances:
 *
 *  ( int, double, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__dscal4(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4);

/*****************************************************************************
 * C declaration of function BlasLevel1::dnrm2.
 *
 * defined instances:
 *
 *  ( int, double[.], int) -> ( double)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__dnrm23(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::sscal.
 *
 * defined instances:
 *
 *  ( int, float, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__sscal4(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4);

/*****************************************************************************
 * C declaration of function BlasLevel1::drotmg.
 *
 * defined instances:
 *
 *  ( double, double, double, double) -> ( double, double, double, double[5])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__drotmg4(SACarg **ret1, SACarg **ret2, SACarg **ret3, SACarg **ret4, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4);

/*****************************************************************************
 * C declaration of function BlasLevel1::daxpy.
 *
 * defined instances:
 *
 *  ( int, double, double[.], int, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__daxpy6(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6);

/*****************************************************************************
 * C declaration of function BlasLevel1::drotm.
 *
 * defined instances:
 *
 *  ( int, double[.], int, double[.], int, double[5]) -> ( double[.], double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__drotm6(SACarg **ret1, SACarg **ret2, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6);

/*****************************************************************************
 * C declaration of function BlasLevel1::snrm2.
 *
 * defined instances:
 *
 *  ( int, float[.], int) -> ( float)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__snrm23(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::srotmg.
 *
 * defined instances:
 *
 *  ( float, float, float, float) -> ( float, float, float, float[5])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__srotmg4(SACarg **ret1, SACarg **ret2, SACarg **ret3, SACarg **ret4, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4);

/*****************************************************************************
 * C declaration of function BlasLevel1::saxpy.
 *
 * defined instances:
 *
 *  ( int, float, float[.], int, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__saxpy6(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6);

/*****************************************************************************
 * C declaration of function BlasLevel1::srotm.
 *
 * defined instances:
 *
 *  ( int, float[.], int, float[.], int, float[5]) -> ( float[.], float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__srotm6(SACarg **ret1, SACarg **ret2, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6);

/*****************************************************************************
 * C declaration of function BlasLevel1::scnrm2.
 *
 * defined instances:
 *
 *  ( int, Structures::complex[.], int) -> ( float)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__scnrm23(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::ddot.
 *
 * defined instances:
 *
 *  ( int, double[.], int, double[.], int) -> ( double)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__ddot5(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::sdot.
 *
 * defined instances:
 *
 *  ( int, float[.], int, float[.], int) -> ( float)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__sdot5(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::drotg.
 *
 * defined instances:
 *
 *  ( double, double, double, double) -> ( double, double, double, double)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__drotg4(SACarg **ret1, SACarg **ret2, SACarg **ret3, SACarg **ret4, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4);

