/*
 * C interface header file for module(s):
 *
 *   - BlasLevel3
 *   - BlasLevel2
 *   - BlasLevel1
 *
 * generated by sac4c 2.1.0-PuurGeluk-260-g7be5 (RELEASE)
 */

#include "sacinterface.h"


/*****************************************************************************
 * User Defined Type ComplexBasics::complex implemented in SaC as double[2]
 *
 * NB: to create a ComplexBasics__complex[300,200], call
 *     SACARGcreateFromPointer (SACTYPE_ComplexBasics__complex, data, 3, 300, 200, 2)
 *     with data being of type double*.
 */

SAC_C_EXTERN SACtypes *SACTYPE_ComplexBasics__complex;


/*****************************************************************************
 * User Defined Type Complex::complex implemented in SaC as double[2]
 *
 * NB: to create a Complex__complex[300,200], call
 *     SACARGcreateFromPointer (SACTYPE_Complex__complex, data, 3, 300, 200, 2)
 *     with data being of type double*.
 */

SAC_C_EXTERN SACtypes *SACTYPE_Complex__complex;


/*****************************************************************************
 * User Defined Type Structures::complex implemented in SaC as double[2]
 *
 * NB: to create a Structures__complex[300,200], call
 *     SACARGcreateFromPointer (SACTYPE_Structures__complex, data, 3, 300, 200, 2)
 *     with data being of type double*.
 */

SAC_C_EXTERN SACtypes *SACTYPE_Structures__complex;



/*****************************************************************************
 * C declaration of function BlasLevel3::dsyrk.
 *
 * defined instances:
 *
 *  ( char, char, int, int, double, double[.,.], int, double, double[.,.], int) -> ( double[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel3__dsyrk10(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10);

/*****************************************************************************
 * C declaration of function BlasLevel3::dsyr2k.
 *
 * defined instances:
 *
 *  ( char, char, int, int, double, double[.,.], int, double[.,.], int, double, double[.,.], int) -> ( double[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel3__dsyr2k12(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11, SACarg *arg12);

/*****************************************************************************
 * C declaration of function BlasLevel3::dgemm.
 *
 * defined instances:
 *
 *  ( char, char, int, int, int, double, double[.,.], int, double[.,.], int, double, double[.,.], int) -> ( double[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel3__dgemm13(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11, SACarg *arg12, SACarg *arg13);

/*****************************************************************************
 * C declaration of function BlasLevel3::ssyrk.
 *
 * defined instances:
 *
 *  ( char, char, int, int, float, float[.,.], int, float, float[.,.], int) -> ( float[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel3__ssyrk10(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10);

/*****************************************************************************
 * C declaration of function BlasLevel3::dtrsm.
 *
 * defined instances:
 *
 *  ( char, char, char, char, int, int, double, double[.,.], int, double[.,.], int) -> ( double[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel3__dtrsm11(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11);

/*****************************************************************************
 * C declaration of function BlasLevel3::ssyr2k.
 *
 * defined instances:
 *
 *  ( char, char, int, int, float, float[.,.], int, float[.,.], int, float, float[.,.], int) -> ( float[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel3__ssyr2k12(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11, SACarg *arg12);

/*****************************************************************************
 * C declaration of function BlasLevel3::dsymm.
 *
 * defined instances:
 *
 *  ( char, char, int, int, double, double[.,.], int, double[.,.], int, double, double[.,.], int) -> ( double[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel3__dsymm12(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11, SACarg *arg12);

/*****************************************************************************
 * C declaration of function BlasLevel3::sgemm.
 *
 * defined instances:
 *
 *  ( char, char, int, int, int, float, float[.,.], int, float[.,.], int, float, float[.,.], int) -> ( float[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel3__sgemm13(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11, SACarg *arg12, SACarg *arg13);

/*****************************************************************************
 * C declaration of function BlasLevel3::strsm.
 *
 * defined instances:
 *
 *  ( char, char, char, char, int, int, float, float[.,.], int, float[.,.], int) -> ( float[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel3__strsm11(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11);

/*****************************************************************************
 * C declaration of function BlasLevel3::ssymm.
 *
 * defined instances:
 *
 *  ( char, char, int, int, float, float[.,.], int, float[.,.], int, float, float[.,.], int) -> ( float[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel3__ssymm12(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11, SACarg *arg12);

/*****************************************************************************
 * C declaration of function BlasLevel3::dtrmm.
 *
 * defined instances:
 *
 *  ( char, char, char, char, int, int, double, double[.,.], int, double[.,.], int) -> ( double[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel3__dtrmm11(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11);

/*****************************************************************************
 * C declaration of function BlasLevel3::strmm.
 *
 * defined instances:
 *
 *  ( char, char, char, char, int, int, float, float[.,.], int, float[.,.], int) -> ( float[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel3__strmm11(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11);

/*****************************************************************************
 * C declaration of function BlasLevel2::dspr.
 *
 * defined instances:
 *
 *  ( char, int, double, double[.], int, double[.]) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dspr6(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6);

/*****************************************************************************
 * C declaration of function BlasLevel2::sgbmv.
 *
 * defined instances:
 *
 *  ( char, int, int, int, int, float, float[.,.], int, float[.], int, float, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__sgbmv13(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11, SACarg *arg12, SACarg *arg13);

/*****************************************************************************
 * C declaration of function BlasLevel2::dspr2.
 *
 * defined instances:
 *
 *  ( char, int, double, double[.], int, double[.], int, double[.]) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dspr28(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8);

/*****************************************************************************
 * C declaration of function BlasLevel2::stpsv.
 *
 * defined instances:
 *
 *  ( char, char, char, int, float[.], float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__stpsv7(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7);

/*****************************************************************************
 * C declaration of function BlasLevel2::dtbmv.
 *
 * defined instances:
 *
 *  ( char, char, char, int, int, double[.,.], int, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dtbmv9(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9);

/*****************************************************************************
 * C declaration of function BlasLevel2::sspr.
 *
 * defined instances:
 *
 *  ( char, int, float, float[.], int, float[.]) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__sspr6(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6);

/*****************************************************************************
 * C declaration of function BlasLevel2::dtrmv.
 *
 * defined instances:
 *
 *  ( char, char, char, int, double[.,.], int, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dtrmv8(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8);

/*****************************************************************************
 * C declaration of function BlasLevel2::dsbmv.
 *
 * defined instances:
 *
 *  ( char, int, int, double, double[*], int, double[*], int, double, double[*], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dsbmv11(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11);

/*****************************************************************************
 * C declaration of function BlasLevel2::sspr2.
 *
 * defined instances:
 *
 *  ( char, int, float, float[.], int, float[.], int, float[.]) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__sspr28(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8);

/*****************************************************************************
 * C declaration of function BlasLevel2::stbmv.
 *
 * defined instances:
 *
 *  ( char, char, char, int, int, float[.,.], int, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__stbmv9(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9);

/*****************************************************************************
 * C declaration of function BlasLevel2::dtpmv.
 *
 * defined instances:
 *
 *  ( char, char, char, int, double[.], double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dtpmv7(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7);

/*****************************************************************************
 * C declaration of function BlasLevel2::strmv.
 *
 * defined instances:
 *
 *  ( char, char, char, int, float[.,.], int, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__strmv8(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8);

/*****************************************************************************
 * C declaration of function BlasLevel2::ssbmv.
 *
 * defined instances:
 *
 *  ( char, int, int, float, float[*], int, float[*], int, float, float[*], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__ssbmv11(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11);

/*****************************************************************************
 * C declaration of function BlasLevel2::dspmv.
 *
 * defined instances:
 *
 *  ( char, int, double, double[.], double[.], int, double, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dspmv9(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9);

/*****************************************************************************
 * C declaration of function BlasLevel2::dger.
 *
 * defined instances:
 *
 *  ( int, int, double, double[.], int, double[.], int, double[.,.], int) -> ( double[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dger9(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9);

/*****************************************************************************
 * C declaration of function BlasLevel2::stpmv.
 *
 * defined instances:
 *
 *  ( char, char, char, int, float[.], float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__stpmv7(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7);

/*****************************************************************************
 * C declaration of function BlasLevel2::dsyr.
 *
 * defined instances:
 *
 *  ( char, int, double, double[*], int, double[.,.], int) -> ( double[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dsyr7(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7);

/*****************************************************************************
 * C declaration of function BlasLevel2::sspmv.
 *
 * defined instances:
 *
 *  ( char, int, float, float[.], float[.], int, float, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__sspmv9(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9);

/*****************************************************************************
 * C declaration of function BlasLevel2::sger.
 *
 * defined instances:
 *
 *  ( int, int, float, float[.], int, float[.], int, float[.,.], int) -> ( float[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__sger9(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9);

/*****************************************************************************
 * C declaration of function BlasLevel2::dsyr2.
 *
 * defined instances:
 *
 *  ( char, int, double, double[*], int, double[*], int, double[.,.], int) -> ( double[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dsyr29(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9);

/*****************************************************************************
 * C declaration of function BlasLevel2::ssyr.
 *
 * defined instances:
 *
 *  ( char, int, float, float[*], int, float[.,.], int) -> ( float[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__ssyr7(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7);

/*****************************************************************************
 * C declaration of function BlasLevel2::ssyr2.
 *
 * defined instances:
 *
 *  ( char, int, float, float[*], int, float[*], int, float[.,.], int) -> ( float[.,.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__ssyr29(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9);

/*****************************************************************************
 * C declaration of function BlasLevel2::dgemv.
 *
 * defined instances:
 *
 *  ( char, int, int, double, double[.,.], int, double[.], int, double, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dgemv11(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11);

/*****************************************************************************
 * C declaration of function BlasLevel2::dtbsv.
 *
 * defined instances:
 *
 *  ( char, char, char, int, int, double[.,.], int, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dtbsv9(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9);

/*****************************************************************************
 * C declaration of function BlasLevel2::dtrsv.
 *
 * defined instances:
 *
 *  ( char, char, char, int, double[.,.], int, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dtrsv8(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8);

/*****************************************************************************
 * C declaration of function BlasLevel2::dsymv.
 *
 * defined instances:
 *
 *  ( char, int, double, double[*], int, double[.], int, double, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dsymv10(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10);

/*****************************************************************************
 * C declaration of function BlasLevel2::sgemv.
 *
 * defined instances:
 *
 *  ( char, int, int, float, float[.,.], int, float[.], int, float, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__sgemv11(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11);

/*****************************************************************************
 * C declaration of function BlasLevel2::dgbmv.
 *
 * defined instances:
 *
 *  ( char, int, int, int, int, double, double[.,.], int, double[.], int, double, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dgbmv13(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10, SACarg *arg11, SACarg *arg12, SACarg *arg13);

/*****************************************************************************
 * C declaration of function BlasLevel2::stbsv.
 *
 * defined instances:
 *
 *  ( char, char, char, int, int, float[.,.], int, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__stbsv9(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9);

/*****************************************************************************
 * C declaration of function BlasLevel2::dtpsv.
 *
 * defined instances:
 *
 *  ( char, char, char, int, double[.], double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__dtpsv7(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7);

/*****************************************************************************
 * C declaration of function BlasLevel2::strsv.
 *
 * defined instances:
 *
 *  ( char, char, char, int, float[.,.], int, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__strsv8(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8);

/*****************************************************************************
 * C declaration of function BlasLevel2::ssymv.
 *
 * defined instances:
 *
 *  ( char, int, float, float[*], int, float[.], int, float, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel2__ssymv10(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7, SACarg *arg8, SACarg *arg9, SACarg *arg10);

/*****************************************************************************
 * C declaration of function BlasLevel1::idamax.
 *
 * defined instances:
 *
 *  ( int, double[.], int) -> ( int)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__idamax3(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::dcopy.
 *
 * defined instances:
 *
 *  ( int, double[.], int, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__dcopy5(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::dswap.
 *
 * defined instances:
 *
 *  ( int, double[.], int, double[.], int) -> ( double[.], double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__dswap5(SACarg **ret1, SACarg **ret2, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::drot.
 *
 * defined instances:
 *
 *  ( int, double[.], int, double[.], int, double, double) -> ( double[.], double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__drot7(SACarg **ret1, SACarg **ret2, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7);

/*****************************************************************************
 * C declaration of function BlasLevel1::dsdot.
 *
 * defined instances:
 *
 *  ( int, float[.], int, float[.], int) -> ( double)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__dsdot5(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::srotg.
 *
 * defined instances:
 *
 *  ( float, float, float, float) -> ( float, float, float, float)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__srotg4(SACarg **ret1, SACarg **ret2, SACarg **ret3, SACarg **ret4, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4);

/*****************************************************************************
 * C declaration of function BlasLevel1::isamax.
 *
 * defined instances:
 *
 *  ( int, float[.], int) -> ( int)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__isamax3(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::scopy.
 *
 * defined instances:
 *
 *  ( int, float[.], int, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__scopy5(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::sswap.
 *
 * defined instances:
 *
 *  ( int, float[.], int, float[.], int) -> ( float[.], float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__sswap5(SACarg **ret1, SACarg **ret2, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::srot.
 *
 * defined instances:
 *
 *  ( int, float[.], int, float[.], int, float, float) -> ( float[.], float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__srot7(SACarg **ret1, SACarg **ret2, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6, SACarg *arg7);

/*****************************************************************************
 * C declaration of function BlasLevel1::dasum.
 *
 * defined instances:
 *
 *  ( int, double[.], int) -> ( double)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__dasum3(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::sdsdot.
 *
 * defined instances:
 *
 *  ( int, float, float[.], int, float[.], int) -> ( float)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__sdsdot6(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6);

/*****************************************************************************
 * C declaration of function BlasLevel1::sasum.
 *
 * defined instances:
 *
 *  ( int, float[.], int) -> ( float)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__sasum3(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::dscal.
 *
 * defined instances:
 *
 *  ( int, double, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__dscal4(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4);

/*****************************************************************************
 * C declaration of function BlasLevel1::dnrm2.
 *
 * defined instances:
 *
 *  ( int, double[.], int) -> ( double)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__dnrm23(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::sscal.
 *
 * defined instances:
 *
 *  ( int, float, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__sscal4(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4);

/*****************************************************************************
 * C declaration of function BlasLevel1::drotmg.
 *
 * defined instances:
 *
 *  ( double, double, double, double) -> ( double, double, double, double[5])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__drotmg4(SACarg **ret1, SACarg **ret2, SACarg **ret3, SACarg **ret4, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4);

/*****************************************************************************
 * C declaration of function BlasLevel1::daxpy.
 *
 * defined instances:
 *
 *  ( int, double, double[.], int, double[.], int) -> ( double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__daxpy6(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6);

/*****************************************************************************
 * C declaration of function BlasLevel1::drotm.
 *
 * defined instances:
 *
 *  ( int, double[.], int, double[.], int, double[5]) -> ( double[.], double[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__drotm6(SACarg **ret1, SACarg **ret2, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6);

/*****************************************************************************
 * C declaration of function BlasLevel1::snrm2.
 *
 * defined instances:
 *
 *  ( int, float[.], int) -> ( float)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__snrm23(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::srotmg.
 *
 * defined instances:
 *
 *  ( float, float, float, float) -> ( float, float, float, float[5])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__srotmg4(SACarg **ret1, SACarg **ret2, SACarg **ret3, SACarg **ret4, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4);

/*****************************************************************************
 * C declaration of function BlasLevel1::saxpy.
 *
 * defined instances:
 *
 *  ( int, float, float[.], int, float[.], int) -> ( float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__saxpy6(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6);

/*****************************************************************************
 * C declaration of function BlasLevel1::srotm.
 *
 * defined instances:
 *
 *  ( int, float[.], int, float[.], int, float[5]) -> ( float[.], float[.])
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__srotm6(SACarg **ret1, SACarg **ret2, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5, SACarg *arg6);

/*****************************************************************************
 * C declaration of function BlasLevel1::scnrm2.
 *
 * defined instances:
 *
 *  ( int, Structures::complex[.], int) -> ( float)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__scnrm23(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function BlasLevel1::ddot.
 *
 * defined instances:
 *
 *  ( int, double[.], int, double[.], int) -> ( double)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__ddot5(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::sdot.
 *
 * defined instances:
 *
 *  ( int, float[.], int, float[.], int) -> ( float)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__sdot5(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4, SACarg *arg5);

/*****************************************************************************
 * C declaration of function BlasLevel1::drotg.
 *
 * defined instances:
 *
 *  ( double, double, double, double) -> ( double, double, double, double)
 *
 *****************************************************************************/

SAC_C_EXTERN void BlasLevel1__drotg4(SACarg **ret1, SACarg **ret2, SACarg **ret3, SACarg **ret4, SACarg *arg1, SACarg *arg2, SACarg *arg3, SACarg *arg4);

